name: Cypress Tests pola

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5  # use the explicit version number
        with:
          command: npm run test-allure
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history 
     
    #  - name: Slack Notification
    #     uses: rtCamp/action-slack-notify@v2
    #     env:
    #       SLACK_CHANNEL: general
    #       SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
    #       SLACK_ICON: https://github.com/rtCamp.png?size=48
    #       SLACK_MESSAGE: 'Test terminé :rocket:'
    #       SLACK_TITLE: Pola Testing with Cypress
    #       SLACK_USERNAME: Anthony POLA
    #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history